Add EventsIterator support for Prophesee camera
lava-nc/lava-peripherals pull request #9
Opened 2023-08-13 13:59 UTC by hexu33

2023-09-05 11:02 UTC, mathisrichter requested changes
This needs some higher-level refactoring. We will do a finer-grained review of the code and unit tests once my points have been addressed.

2023-09-05 11:02 UTC, mathisrichter commented on tests/lava/lib/peripherals/dvs/test_prophesee.py
> +USE_EVENTSITERATOR = True
There need to be unit tests for both the ProcessModel using the RawReader as well as the one using the EventsIterator. A global switch for the unit tests that would have to be changed manually before running the tests does not work here.

Please make sure that there are separate tests for the different ProcessModel implementations and that the correct ProcessModels are imported for those tests only.

2023-09-07 08:07 UTC, seowwj commented on src/lava/lib/peripherals/dvs/prophesee_rawreader.py
> +from metavision_core.event_io import EventsIterator
Removed unused imports.

2023-09-07 08:07 UTC, seowwj commented on src/lava/lib/peripherals/dvs/prophesee_rawreader.py
> +from threading import Thread
Removed unused imports.

2023-09-15 07:40 UTC, seowwj commented on src/lava/lib/peripherals/dvs/prophesee_eventsiterator.py
> +    delta_t: Control the size of the time window for collecting events,
We will merge in `EventsIterator` and `RawReader` into a single file, with tagging.

The caveat with tagging is that the current implementation of `select_tag` in `run_config` would require that all other ProcessModels (and not just the Prophesee ProcessModel) be tagged appropriately. For instance, if they use the tag `event_it` then the same tag needs to appear in other ProcessModels as well.

Currently the best way to do select the ProcessModel is to manually create a custom process model map and pass it to the run configuration.

2023-09-15 07:41 UTC, seowwj commented on tests/lava/lib/peripherals/dvs/test_prophesee.py
> +    return height,width
Fixed

2023-09-18 10:33 UTC, mathisrichter requested changes

2023-09-18 10:33 UTC, mathisrichter commented on src/lava/lib/peripherals/dvs/prophesee_rawreader.py
> +# Copyright (C) 2023 Intel Corporation
Is this file still needed? You seem to have ProcessModels for both the EventsIterator and RawReader implementation in the other file.

2023-09-18 10:33 UTC, mathisrichter commented on tests/lava/lib/peripherals/dvs/test_prophesee.py
> +USE_EVENTSITERATOR = True
This comment has not been addressed, yet. As it is, only the ProcessModel with the EventsIterator implementation is being tested by the unit tests. Please remove this global flag and write dedicated tests for the PropheseeCamera Process with its different ProcessModels (i.e., RawReader and EventsIterator).

If there is something blocking you, please do not hesitate to reach out and discuss that with me.

2023-09-24 15:54 UTC, PhilippPlank commented
Hello, I have started a new PR for this change (#18) to enable our automatic unit test runs. Currently our CI pipeline does not work for PRs coming from public forks... 

Please use #18 for future changes! Thanks.

2023-09-24 15:54 UTC, closed without merging